ARG ROS_DISTRO=humble
FROM ros2:${ROS_DISTRO}
ARG ROS_DISTRO=humble

RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-gazebo-ros-pkgs \
    ros-${ROS_DISTRO}-gazebo-ros2-control \
    ros-${ROS_DISTRO}-joint-state-broadcaster \
    && rm -rf /var/lib/apt/lists/*
